[package]
name = "descord"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
description = "A minimal discord api wrapper."
authors = ["Pranjal Patel <pranjalpatel@duck.com>"]
repository = "https://github.com/thatmagicalcat/descord"
readme = "README.md"

[dependencies]
dotenvy = "0.15.7"
env_logger = "0.11.3"
json = "0.12.4"
log = "0.4.21"
tungstenite = { version = "0.21.0", features = ["native-tls"] }
url = "2.5.0"
